% Build the IIR filter coefficients, type can be
% 0 = regular, 1 = highpass, 2 = bandpass
% Highpass and bandpass concatenate the respective filter after the fitting
% to reflectance coefficients, this is useful to mitigate instability in
% long running simulation
function [b,a] = fit_IIR_R(fs, freqs, alpha, order, type, plot_original, plot_fit)
    highpass_window = 50; % Increase these values to remove more band from
    low_bandpass_window = 50; % the respective filter types, in exchange
    high_bandpass_window = 50; % for less low/high end

    if not(type == 0 || type == 1 || type == 2)
        error("type can be 0 (regular yulewalk), 1 (yulewalk + high pass) or 2 (yulewalk + bandpass)")
    end
    if (order - type < 0)
        error("order too low for use with specified type")
    end

    freqs = [0, freqs]; % Add one point at 0 and one at Fs/2
    freqs = [freqs, fs/2];
    norm_freqs = freqs/fs*2; % then normalize in the [0,1] range

    alpha = [alpha, alpha(length(alpha))]; % Duplicate the first and last entry in alpha
    alpha = [alpha(1), alpha];
    R = sqrt(1.0 - alpha); % then convert to reflectance

    order = order - type; % Decrease the order to get the correct final order after concatenation
    if order == 0
        b = interp1(freqs,R,fs/4); % Use interpolated R at the middle frequency
        a = 1;
    else
        [b,a] = yulewalk(order,norm_freqs,R); % Use yulewalk
    end
    order = order + type;

    h1 = dfilt.df1(b,a); % If type = regular, then use the previous step's result
    type_str = "regular";
    plot_tick='';
    if type == 1 % If type = high pass then concatenate a first order highpass
        type_str = "highpass";
        plot_tick=':';
        Wn = highpass_window/fs;
        [b2, a2] = butter(1, Wn, 'high');
        h2 = dfilt.df1(b2,a2);
        hcas = dfilt.cascade(h1,h2);
        [b,a] = tf(hcas);
    else
        if type == 2 % If type = bandpass then concatenate a first order bandpass
            type_str = "bandpass";
            plot_tick='.';
            Wn = [low_bandpass_window/fs, (fs-high_bandpass_window)/fs];
            [b2, a2] = butter(1, Wn, 'bandpass');
            h2 = dfilt.df1(b2,a2);
            hcas = dfilt.cascade(h1,h2);
            [b,a] = tf(hcas);
        end
    end

    plot_db = false;
    cols = rgb2hex(orderedcolors("gem"));
    if (plot_original)
        if plot_db
            R = mag2db(R);
        end
        plot(freqs,R, '-o', 'Color', cols(1), 'DisplayName','Reference')
    end
    if (plot_fit)
        [h,w] = freqz(b,a,1024);
        h = abs(h);
        if (plot_db)
            h = mag2db(h);
        end
        col = cols(order/2 + 1); % This assumes that order is always even
        plot(w/pi*fs/2,h, plot_tick, 'Color', col, 'DisplayName', "IIR order = " + num2str(order) + ", " + type_str)
    end
    if not(isstable(b,a))
        error("Unstable filter found!");
    end
end

% Coefficients taken from
% Oxnard, Stephen, et al. "Frequency-Dependent Absorbing Boundary Implementations in 3D Finite Difference Time Domain Room Acoustics Simulations." Proceedings of EURONOISE, Maastricht, The Netherlands (2015).
materials_freqs = [63 125 250 500 1000 2000 4000];
materials_names = [
    "plaster";
    "wood";
    "concrete"
];
materials_alpha = [
    [0.08 0.08 0.20 0.50 0.40 0.40 0.36]; % plaster
    [0.15 0.15 0.11 0.10 0.07 0.06 0.06]; % wood
    [0.02 0.02 0.03 0.03 0.03 0.04 0.07]  % concrete
];
materials_count = 3;
% Common sample rates
fs_s = [16000, 22050, 32000, 44100, 48000];
% Filter orders
IIR_orders = [2, 4, 8];

% Header file
fid = fopen('../include/dwr3/gen/boundary_reflectance_filters.hpp','wt');
fprintf(fid, '// This file was generated by the scripts/boundary_reflectance_filters_coefficients_generator.m MATLAB script\n');
fprintf(fid, '#ifndef DWR3_BOUNDARY_FILTERS_HPP\n');
fprintf(fid, '#define DWR3_BOUNDARY_FILTERS_HPP\n\n');
fprintf(fid, 'enum class boundary_reflectance_filter_material {\n');
for material_name = materials_names
    fprintf(fid, '\t%s,\n', material_name);
end
fprintf(fid, '};\n\n');
fprintf(fid, "/** Converts from a string to one of the @p boundary_reflectance_filter_material enum's values @throw std::exception if no match is found */\n");
fprintf(fid, 'boundary_reflectance_filter_material boundary_reflectance_filter_material_from_string(const std::string &str);\n\n');
fprintf(fid, "/** Returns a pointer to a static @p boundary_reflectance_filter_coefficients instance, fitted from absorption coefficients @note the returned instance depends on the @p DWR3_BOUNDARY_FILTER_TYPE definition @throw std::runtime_error if the @p sample_rate is not supported @throw std::logic_error for invalid enum values */\n");
fprintf(fid, 'const boundary_reflectance_filter_coefficients *boundary_reflectance_filter_material_to_coefficients(boundary_reflectance_filter_material material, int sample_rate);\n\n');
fprintf(fid, '#endif //DWR3_BOUNDARY_FILTERS_HPP\n');
fclose(fid);

% Source file
fid = fopen('../src/gen/boundary_reflectance_filters.cpp','wt');
fprintf(fid, '// This file was generated by the scripts/boundary_reflectance_filters_coefficients_generator.m MATLAB script\n');
fprintf(fid, '#include <dwr3/dwr3.hpp>\n\n');
fprintf(fid, 'static_assert(DWR3_BOUNDARY_FILTER_TYPE == DWR3_BOUNDARY_FILTER_TYPE_REGULAR ^ DWR3_BOUNDARY_FILTER_TYPE == DWR3_BOUNDARY_FILTER_TYPE_HIGHPASS ^ DWR3_BOUNDARY_FILTER_TYPE == DWR3_BOUNDARY_FILTER_TYPE_BANDPASS);\n\n');
for type = 0:2
    fprintf(fid, '#if DWR3_BOUNDARY_FILTER_TYPE == DWR3_BOUNDARY_FILTER_TYPE_');
    if type == 0
        fprintf(fid, 'REGULAR\n');
    else
        if type == 1
            fprintf(fid, 'HIGHPASS\n');
        else
            fprintf(fid, 'BANDPASS\n');
        end
    end
    for order = IIR_orders
        fprintf(fid, '#if (DWR3_BOUNDARY_FILTER_ORDER) == %d\n', order);
        for i = 1:materials_count
            for fs = fs_s
                fprintf(fid, 'static constexpr dwr3::boundary_reflectance_filter_coefficients %s_%i = {', materials_names(i), fs);
                [b,a] = fit_IIR_R(fs, materials_freqs, materials_alpha(i,:), order, type, false, false);
                fprintf(fid, "{%s},{%s}", strip(sprintf("%.16f,", b), ","), strip(sprintf("%.16f,", a), ","));
                fprintf(fid, '};\n');
            end
        end
        fprintf(fid, '#endif\n');
    end
    fprintf(fid, '#endif\n\n');
end
fprintf(fid, 'dwr3::boundary_reflectance_filter_material boundary_reflectance_filter_material_from_string(const std::string &str) {\n');
for i = 1:materials_count
    fprintf(fid, '\tif (str == "%s") return dwr3::boundary_reflectance_filter_material::%s;\n', material_name(i), material_name(i));
end
fprintf(fid, '\tthrow std::logic_error("Unknown material string \\"" + str + "\\"");\n');
fprintf(fid, '}\n\n');
fprintf(fid, 'const dwr3::boundary_reflectance_filter_coefficients *dwr3::boundary_reflectance_filter_material_to_coefficients(const boundary_reflectance_filter_material material, const int sample_rate) {\n');
fprintf(fid, '\tswitch (material) {\n');
for i = 1:materials_count
    fprintf(fid, '\t\tcase boundary_reflectance_filter_material::%s: switch (sample_rate) {\n', materials_names(i));
    for fs = fs_s
       fprintf(fid, '\t\t\tcase %i: return &%s_%i;\n', fs, materials_names(i), fs);
    end
    fprintf(fid, '\t\t\tdefault: throw std::runtime_error(std::string("Sample rate ") + std::to_string(sample_rate) + " is not supported");\n');
    fprintf(fid, '\t\t}\n');
end
fprintf(fid, '\t\tdefault: throw std::logic_error("Unknown boundary_reflectance_filter_material enum");\n');
fprintf(fid, '\t}\n');
fprintf(fid, '\t\n');
fprintf(fid, '}\n');
fclose(fid);

% Diagnostic plots
for fs = fs_s
    for i = 1:materials_count
        first = true;
        figure
        hold on
        for order = IIR_orders
            for type = [0, 1, 2]
                fit_IIR_R(fs, materials_freqs, materials_alpha(i,:), order, type, first, true);
                first = false;
            end
        end
        set(gca,XScale="log")
        set(gca, 'XTickLabel', get(gca, 'XTick'))
        set(gca, 'XMinorTick', 'on')
        xlabel('Hz')
        ylabel('|R|')
        grid
        title(materials_names(i) + ", Fs = " + num2str(fs));
        legend('Location', 'southeast');
        hold off
    end
end